### PR TITLE
Time and order feature added

### PR DESCRIPTION
**Pull request by mithunmunsi**
Just the design. functionality not working yet. I did little changes to the style of drawer `height: auto from 760px and in window> flex-basis: 15%`. I feel it looks good in the design.

### CODE REVIEW

**Review by aj-kivimaki — CHANGES_REQUESTED** [review]
those styles on index.css will affect on other's styling

you will need take your styles for the DateAndOrder out from index.css and put them on a separate file. use a main class (for example date-and-order) and nest all your related classes, so that your '.btn' class does not affect on other code outside of your component.

see windows.tsx/windows.css for an example

**Comment by mithunmunsi** [comment]
thnx for feedback. styles are seperated now.

**Comment by aj-kivimaki** [comment]
you are still missing the main class where you should nest all of your styles, just moving them to another files does not separate them yet

in dateandorderpicker.tss add main class for the first div after return

Näyttökuva 2024-4-5 kello 8 18 52

if your main class were .windows you would use it like this
(just change to corresponding classes)

Näyttökuva 2024-4-5 kello 8 24 44

**Comment by mithunmunsi** [comment]
does it work now?

**Comment by aj-kivimaki** [comment]
please read again the instructions

**Review by aj-kivimaki — APPROVED** [review]

**Pull request merged**
